# Method to create heatmap from herbarium sample HPLC data
library(ggplot2)
library(plyr)
library(dplyr)
library(tibble)
library(cowplot)
library(ggforce)
library(stats)
library(tidyr)

# Read metabolite data from .csv file -------------------------------------------------------------
rawData <- read.csv(file="C:/Users/Bryce/Documents/scutellariaMetabolites/data/metaboliteDataHerbarium1-30.csv", na.strings=c("", "NA"), header=TRUE)
rawData[, 1] <- as.character(rawData[, 1])

# Define functions for interpreting injection names -----------------------------------------------
herbariumList <- read.csv(file="C:/Users/Bryce/Documents/scutellariaMetabolites/data/herbariumList.csv")

getSampleName <- function(injectionName, nameList){
  sampleName <- nameList[injectionName==nameList$Label, 3]
  if(length(sampleName)==0){
    print("TRUE")
  }
  return(as.character(sampleName))
}

# Define function to convert peak area data into ppm using calibration samples --------------------
ppmConversion <- function(peakArea, metaboliteName, mix1Rows, mix2Rows, rawData=rawData){
  if(sum(grepl(metaboliteName, colnames(rawData)[2:9]))==1){ #metabolite is in mix 1
    calibrations <- data.frame(ppm=c(0.1, 0.5, 1, 5, 10, 25, 50, 100), area=rawData[[metaboliteName]][mix1Rows])
  }else{ #metabolite is in mix 2
    calibrations <- data.frame(ppm=c(0.1, 0.5, 1, 5, 10, 25, 50, 100), area=rawData[[metaboliteName]][mix2Rows])
  }
  convFactor <- lm(formula=ppm~area+0, data=calibrations)[[1]][[1]]
  ppm <- peakArea*convFactor
  return(ppm)
}

rawData <- rawData[!grepl("15mix", rawData$injection), ]
row.names(rawData) <- 1:nrow(rawData)

# Create data frame with processed data -----------------------------------------------------------
herbariumData <- data.frame(
  variety=sapply(rawData$injection[29:72], getSampleName, nameList=herbariumList),
  apigenin=sapply(rawData$apigenin[29:72], ppmConversion, metaboliteName="apigenin", mix1Rows=11:18, mix2Rows=20:27, rawData=rawData),
  apigeninG=sapply(rawData$apigeninG[29:72], ppmConversion, metaboliteName="apigeninG", mix1Rows=11:18, mix2Rows=20:27, rawData=rawData),
  scutellarein=sapply(rawData$scutellarein[29:72], ppmConversion, metaboliteName="scutellarein", mix1Rows=11:18, mix2Rows=20:27, rawData=rawData),
  scutellarin=sapply(rawData$scutellarin[29:72], ppmConversion, metaboliteName="scutellarin", mix1Rows=11:18, mix2Rows=20:27, rawData=rawData),
  hispidulin=sapply(rawData$hispidulin[29:72], ppmConversion, metaboliteName="hispidulin", mix1Rows=11:18, mix2Rows=20:27, rawData=rawData),
  hispidulinG=sapply(rawData$hispidulinG[29:72], ppmConversion, metaboliteName="hispidulinG", mix1Rows=11:18, mix2Rows=20:27, rawData=rawData),
  chrysin=sapply(rawData$chrysin[29:72], ppmConversion, metaboliteName="chrysin", mix1Rows=11:18, mix2Rows=20:27, rawData=rawData),
  chrysinG=sapply(rawData$chrysinG[29:72], ppmConversion, metaboliteName="chrysinG", mix1Rows=11:18, mix2Rows=20:27, rawData=rawData),
  wogonin=sapply(rawData$wogonin[29:72], ppmConversion, metaboliteName="wogonin", mix1Rows=11:18, mix2Rows=20:27, rawData=rawData),
  wogonoside=sapply(rawData$wogonoside[29:72], ppmConversion, metaboliteName="wogonoside", mix1Rows=11:18, mix2Rows=20:27, rawData=rawData),
  baicalein=sapply(rawData$baicalein[29:72], ppmConversion, metaboliteName="baicalein", mix1Rows=11:18, mix2Rows=20:27, rawData=rawData),
  baicalin=sapply(rawData$baicalin[29:72], ppmConversion, metaboliteName="baicalin", mix1Rows=11:18, mix2Rows=20:27, rawData=rawData),
  oroxylinA=sapply(rawData$oroxylinA[29:72], ppmConversion, metaboliteName="oroxylinA", mix1Rows=11:18, mix2Rows=20:27, rawData=rawData),
  oroxyloside=sapply(rawData$oroxyloside[29:72], ppmConversion, metaboliteName="oroxyloside", mix1Rows=11:18, mix2Rows=20:27, rawData=rawData),
  acetoside=sapply(rawData$acetoside[29:72], ppmConversion, metaboliteName="acetoside", mix1Rows=11:18, mix2Rows=20:27, rawData=rawData)
)

# Calculate means for herbarium varieties with >1 samples  ----------------------------------------
herbariumData <- aggregate(herbariumData[ , c(2:16)], by=list(herbariumData$variety), mean, na.rm=TRUE)
colnames(herbariumData)[1] <- "variety"

# Convert data into tidy format for for plotting with ggplot --------------------------------------
herbariumData <- gather(herbariumData, "metabolite", "concentration", 2:16)

# Reorder metabolites as they will appear in heatmap ----------------------------------------------
metaboliteOrder <- c("oroxyloside", "oroxylinA", "hispidulinG", "hispidulin", "chrysin", "chrysinG", "apigenin", "apigeninG", "acetoside", "scutellarein", "scutellarin", "baicalin", "baicalein", "wogonin", "wogonoside")
herbariumData$metabolite <- factor(herbariumData$metabolite, levels=metaboliteOrder)

# Combine herbarium data with averaged organ-specific data generated by dataVisHPLC_v2 ------------
allData <- allData[ , -c(4:6, 8)]
allData <- allData %>%
  group_by(variety, metabolite) %>%
  summarise(concentration=mean(meanConc))
allData$variety <- factor(allData$variety)
colnames(allData) <- colnames(herbariumData)
allDataTotal <- dplyr::bind_rows(allData, herbariumData)
allDataTotal <- allDataTotal %>%
  filter(!grepl("racemosa MS", variety)) %>%
  filter(!grepl("racemosa SC", variety)) %>%
  filter(!grepl("racemosa 071119", variety))
allDataTotal$variety <- factor(allDataTotal$variety)
levels(allDataTotal$variety)[29] <- "racemosa"

#Fix errors in naming
levels(allDataTotal$variety)[levels(allDataTotal$variety)=="hastafolia"] <- "hastifolia"
# Define function to capitalize first letter of a string
capStr <- function(y) {
  c <- strsplit(y, " ")[[1]]
  paste(toupper(substring(c, 1,1)), substring(c, 2),
        sep="", collapse=" ")
}
allDataTotal$metabolite <- factor(sapply(as.character(allDataTotal$metabolite), capStr))


# Create heatmap ----------------------------------------------------------------------------------
heatmap <- ggplot(data=allDataTotal) +
  geom_raster(mapping=aes(x=variety, y=metabolite, fill=concentration)) +
  scale_fill_gradientn(colours=c("#FFFFFFFF", "#0066CC")) +
  coord_fixed() +
  labs(x="Species", y="Metabolite", fill="Concentration \n(ppm)") +
  theme(axis.text.x=element_text(angle=90, vjust=0.5, hjust=1, color="#000000"), text=element_text(size=16, color="#000000"), 
        legend.position="right", legend.direction = "vertical")
print(heatmap)

